name:                musikell
version:             0.1.0.0
github:              "Allison-Turner/musikell"
license:             BSD3
author:              "Mark Barbone, Joey Rudek, Allison Turner, and James Yuan"
maintainer:          "example@example.com"
copyright:           "2021 Mark Barbone, Joey Rudek, Allison Turner, and James Yuan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Allison-Turner/musikell#readme>

dependencies:
- base >= 4.7 && < 5
- brick
- bytestring
- directory
- text
- vty
- aeson
- array
- sdl2
- sdl2-mixer

library:
  source-dirs: src

executables:
  musikell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - musikell
    - text

tests:
  cse230-f21-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - musikell
